// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NModal: typeof import('naive-ui')['NModal']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
}

export { }
